=== Hossein3041/programmieren_3/src/aufgabenblatt01/script01.dtd
<?xml version ="1.0" encoding="UTF-8"?>
        <!-- file: script01.dtd -->
        <!-- einfache DTD fuer Skript-Dateien -->
        <!ELEMENT courseDoc (title, abstract, chapter+)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT abstract (#PCDATA)>
        <!ELEMENT chapter (heading, para+, sparePages?)>
        <!ELEMENT heading (#PCDATA)>
        <!ELEMENT para (#PCDATA)>
        <!ELEMENT sparePages EMPTY>

=== Hossein3041/programmieren_3/src/aufgabenblatt01/script02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE courseDoc SYSTEM "C:\Users\hosse\IdeaProjects\XMLHossein\src\aufgabenblatt01\script01.dtd">
<courseDoc>
    <title>2. Testen von XML-Dokumenten</title>
    <abstract>Zusammenfassung...</abstract>
    <chapter>
        <heading>Erstes Kapitel</heading>
        <para> Absatz eins</para>
        <para> Absatz zwei</para>
    </chapter>
    <chapter>
        <heading>Zweites Kapitel</heading>
        <para> Absatz eins</para>
        <sparePages/>
    </chapter>
    <chapter>
        <heading>Drittes Kapitel</heading>
        <para> Absatz eins</para>
        <sparePages/>
    </chapter>
</courseDoc>

=== Hossein3041/programmieren_3/src/aufgabenblatt01/script03.xml
<?cxml version="1.0" encoding="UTF-8"?>
<!DOCTYPE courseDoc SYSTEM "C:\Users\hosse\IdeaProjects\XMLHossein\src\aufgabenblatt01\script01.dtd">
<courseDoc>
    <title>Das ist der Title</title>
    <abstract>Zusammenfassung...</abstract>
    <chapter>
        <heading>Hallo Welt</heading>
        <para> Absatz eins</para>
        <para> Absatz zwei</para>
    </chapter>
    <chapter>
        <heading>Hallo Teufel</heading>
        <para> Absatz eins</para>
        <sparePages/>
    </chapter>
    <chapter>
        <heading>Hallo Tsch√ºss</heading>
        <para> Absatz eins</para>
    </chapter>
</courseDoc>

=== Hossein3041/programmieren_3/src/aufgabenblatt01/script01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE courseDoc SYSTEM "C:\Users\hosse\IdeaProjects\XMLHossein\src\aufgabenblatt01\script01.dtd">
<courseDoc>
    <title>1. Testen von XML-Dokumenten</title>
    <abstract>Kurze Zusammenfassung</abstract>
    <chapter>
        <heading>Hallo Welt</heading>
        <para> Absatz eins</para>
        <para> Absatz zwei</para>
    </chapter>
    <chapter>
        <heading>Welt Hallo</heading>
        <para> Absatz eins</para>
    </chapter>
    <chapter>
        <heading>Hallo Hallo Welt Welt</heading>
        <para> Absatz eins</para>
        <sparePages/>
    </chapter>
</courseDoc>
