=== Hossein3041/programmieren_3/src/Erstes_Assignment_02/Assignment1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Aufgabe: Bestand der Informatik-Rechnerlabore erfassen -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" targetNamespace="assignment01.webprog.de" xmlns:xt="assignment01.webprog.de" xmlns="assignment01.webprog.de">
	<xs:element name='Labordaten'>
		<xs:complexType>
		<xs:sequence>
			<!--
			Elementdeklaration für Labor/ Labore
			Attribut name stellt den namen von dem Element, Attribut, etc. dar:
			Beispiel: <xs:element name="Labor" ...         der Name des Elements heißt Labor...
			minOccurs maxOccurs als Attribut sind für die Angabe der Anzahl des Elements:
			minOccurs"1" heißt für Mindestens 1.
			maxOccurs="unbounded" heißt, keine Grenze nach oben für Anzahl
			-->

			<xs:element name="Labor" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>

					<xs:sequence>
							<!-- Für Jedes Labor-Element, für Computer ...
							Das Attribut type ... definiert weitere Unterlemente, Attribute und etc. für das Element: Beispiel für Computertype - Erklärung unten...
							-->
							<xs:element name="Computer" type="ComputerType" minOccurs="1" maxOccurs="unbounded">
								<!--
								 Unique ist für die Eindeutigkeit einer Sache:
								 Mit Selector wählt man die Definition des Pfades.
								 Mit field wählt man, woraus sich die Eindeutigkeit beziehen soll: Beim Beispiel <xs:field xpath="@Id"/> soll das Attribut als ID, unique sein.
								 -->
								<xs:unique name="SoftwareaufRechner">
        							<xs:selector xpath=".//xt:Software2"/>
     			   					<xs:field xpath="@Id"/>
   			 					</xs:unique>
   			 					<!-- Software soll Computer spezifisch Unique sein, nicht über mehrere Computer in einem Labor oder insgesamt -->
							</xs:element>

							<!-- ... Element für Software ... -->
							<xs:element name="Software" type="Softwareart" minOccurs="0" maxOccurs="unbounded">

							</xs:element>

							<!-- ... Element für weitere Geraete ... -->
							<xs:element name="weitere_Geraete" type="Weiteres" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<!-- FÜr jedes Laborelement, das Attribut Name und Raumnummer -->
					<xs:attribute name="Name" type="xs:string"/>
					<xs:attribute name="Raum" type="xs:string"/>
				</xs:complexType>
				 <!-- Softwarename ist eindeutig -->
				<xs:unique name="UniqueRechnerSoftwareKey">
        			<xs:selector xpath=".//xt:Softwarename"/>
     			   <xs:field xpath="."/>
   			 	</xs:unique>
				<!-- Software ist eindeutig:
				Wir haben hierbei für das Attribut ID von dem Element Software, einen Schlüssel deklariert, durch <xs:key> ... Der Name der Schlüssel ist niqueRechnerSoftware
				-->
   			 	<xs:key name="UniqueRechnerSoftware">
        			<xs:selector xpath=".//xt:Software"/>
     			   <xs:field xpath="@ID"/>
   			 	</xs:key>
				<!-- Jeder Rechner ist eindeutig, durch Schlüssel -->
   			 	<xs:key name="UniqueRechner">
        			<xs:selector xpath=".//xt:Computer"/>
     			   <xs:field xpath="@RechnerId"/>
   			 	</xs:key>
				<!-- Weitere Geräte ist eindeutig -->
   			 	<xs:key name="UniqueEquipment">
        			<xs:selector xpath=".//xt:weitere_Geraete"/>
     			   <xs:field xpath="@WeiteresID"/>
   			 	</xs:key>
				<!--
				Mit keyref deklariert man einen Fremdschlüssel
				Fremdschlüssel referenziert auf Schlüssel von SoftwareID
				Die ID muss als Schlüssel einer Software vorhanden sein
				 -->
   			 	<xs:keyref name="Softwareid" refer="UniqueRechnerSoftware">
           			<xs:selector xpath=".//xt:Software2"/>
         		   	<xs:field xpath="@Id"/>
      			 </xs:keyref>

			</xs:element>
		</xs:sequence>
		</xs:complexType>
		<!-- Raum von Labor ist eindeutig, durch Attribut -->
		 <xs:unique name="UniqueLabor">
        	<xs:selector xpath=".//xt:Labor"/>
     		<xs:field xpath="@Raum"/>
   		</xs:unique>
		<!-- Name von Labor ist eindeutig, durch Attribut -->
   		<xs:unique name="UniqueLaborName">
        	<xs:selector xpath=".//xt:Labor"/>
     		<xs:field xpath="@Name"/>
   		</xs:unique>

	</xs:element>
	<xs:complexType name="ComputerType">
		<!-- Beispiel Fort: ... -->

		<xs:sequence>
			<!-- Weitere Unterelemente für Computer deklarieren -->
			<xs:element name="Betriebssystem" type="xs:string"/>
			<xs:element name="Anschaffung" type="xs:date"/>
			<xs:element name="Erweiterungen" type="Mehr" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Rechnerbeschreibung" type="Beschreibungstyp"/>
			<xs:element name="Rechnerbesonderheiten" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Software2" type="Softwareref" minOccurs="0" maxOccurs="unbounded">


			</xs:element>
		</xs:sequence>
		<!-- Attribut für Computer deklarieren -->
		<xs:attribute name="RechnerId" type="xs:string"/>

	</xs:complexType>

	<xs:complexType name="Softwareart">
		<!-- Weitere Beschreibung als Element für Software hinzufügen -->
		<xs:sequence>
			<xs:element name="Softwarename" type="xs:string">

			</xs:element>
			<xs:element name="Softwarebeschreibung" type="Beschreibungstyp"/>
			<xs:element name="Softwarebesonderheiten" type="xs:string"/>
		</xs:sequence>
		<!-- Attribut als ID für Software hinzufügen -->
		<xs:attribute name="ID" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="Softwareref">
		<!-- Für Software 2, Attribute hinzufügen, für lizenziert und ID -->
		<xs:sequence>
		</xs:sequence>
		<xs:attribute name="lizensiert" type="xs:boolean" default="true"/>
		<xs:attribute name="Id" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="Weiteres">
		<!-- Für weitere Geräte, Elemente hinzufügen, für Art des Softwares und für die Beschreibung dessen -->
		<xs:sequence>
			<xs:element name="Art" type="xs:string"/>
			<xs:element name="Beschreibung" type="Beschreibungstyp"/>
		</xs:sequence>
		<!-- Attribut für weitere Geräte -->
		<xs:attribute name="WeiteresID" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="Beschreibungstyp" mixed="true">
		<!-- Hersteller für die Angabe von Hersteller, für alles was einen Hersteller hat. -->
		<xs:sequence>
			<xs:element name="hersteller" type="xs:string" minOccurs="0" maxOccurs="unbounded" form="qualified"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Mehr">
		<!-- Für Erweiterungen eines Computers, sollen Beschreibungen für Hersteller und Besonderheiten eines Computers als Elemente deklariert sein. -->
		<xs:sequence>
			<xs:element name="Beschreibung" type="Beschreibungstyp"/>
			<xs:element name="Besonderheiten" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Hossein3041/programmieren_3/src/Erstes_Assignment_02/Assignment1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Assignment1.xsl"?>
<!-- Stylesheet zum anzeigen der Datei im Browser eingebunden -->
<Labordaten 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="assignment01.webprog.de Assignment1.xsd"
    xmlns="assignment01.webprog.de">
    <!-- Deafult Namensraum Implizit deklariert, verbindung zu XML Schema über xsi,  Labordaten als Wurzelement-->
    <Labor Name="Labor01" Raum="Raum01">
    <!-- Name und Labor unique, um sicherzustellen, dass sie unique sind -->
    <!--Einzelne Labore Kinder von dem Wurzelelement (Labordaten)-->
        <Computer RechnerId="Rechner01">
        <!-- Id als Attribut, gilt nur der eindeutugen identifizierung der Rechner,
        Unique Identifier aus unserer Sicht als Attribut sinnvoll muss keine Daten erhalten dient nur
        der eindeutigen zuweisung-->
            <Betriebssystem>Linux</Betriebssystem>
            <Anschaffung>2002-09-24</Anschaffung>
            <Erweiterungen>
            	<Beschreibung>1 TB Festplatte von <hersteller>SeaGate</hersteller> nachgerüstet </Beschreibung>
            </Erweiterungen>
            <Rechnerbeschreibung>Leistungsstarker <hersteller>Lenovo</hersteller> Rechner, für Virtual Reality Programmierung geeignet
           		 mit Grafikkarte von <hersteller>NVIDIA</hersteller>.
            </Rechnerbeschreibung>
            <Rechnerbesonderheiten>Kaputt,in Reparatur</Rechnerbesonderheiten>
            <!--Daten vonder Aufgabe gefordert, als Element, da es für uns sinnvoller war daten, auf die man öfter zugreifen muss und deren Inhalt man braucht
            als element zu modellieren, Beschreibungen mixed content ansonsten nur Text -->
            <Software2 lizensiert="true" Id="Java"/>
            <!-- Ref und lizensiert als Attribut, werden vergliechen aber nicht ausgelesen, daher Attribute, lizensiert default wert true, in diesem Fall spezifisch
            geschrieben auch wenn es nicht nötig ist -->
        </Computer>
        <Computer RechnerId="Rechner02">
            <Betriebssystem>Windows</Betriebssystem>
            <Anschaffung>2002-01-30</Anschaffung>
            <Erweiterungen>
            	<Beschreibung> Grafikkarte von <hersteller>NVIDIA</hersteller> nachgerüstet. </Beschreibung>
            </Erweiterungen>
            <Rechnerbeschreibung>   
                  Perfekt für einfache Programmierung.
            </Rechnerbeschreibung>
            <Rechnerbesonderheiten>Gehäuse beschädigt</Rechnerbesonderheiten>
            <Software2 lizensiert="true" Id="Eclipse"/>
            <!-- Software andere, darf nicht 2 mal dieselbe enthalten auf demselben Rechner muss als SoftwareID vorhanden sein -->
        </Computer>
        <Computer RechnerId="Rechner03">
            <Betriebssystem>Windows</Betriebssystem>
            <Anschaffung>2002-04-25</Anschaffung>
            <Erweiterungen>
            <Beschreibung> Hallo diese Gra-Ka ist von<hersteller>NVIDIA</hersteller>  </Beschreibung>     
            </Erweiterungen>
            <!-- Erweiterungen,Rechnerbesonderheiten und Software2 als einzigste in der Deklaration nicht nötig, können auch weggelassen werden -->
            <Rechnerbeschreibung>  
            		Eher für allgemeine Programmierung vorgesehen, nicht so leistungsstark.
            		Von <hersteller>HP</hersteller>.
            		Momentan nicht nutzbar.
            </Rechnerbeschreibung>
            <Rechnerbesonderheiten>Monitor und Tastatur fehlen</Rechnerbesonderheiten>
            <Software2 lizensiert="false" Id="VIM"/>
            <Software2 lizensiert="true" Id="Eclipse"/>
            <!-- Mehrere mit verschiedenen Werten möglich -->
        </Computer>
         <Software ID="OXygen">
            <Softwarename>Oxygen</Softwarename>
            <Softwarebeschreibung>
            		Plug-In
                    <hersteller>Oxygen</hersteller>
            </Softwarebeschreibung>
            <Softwarebesonderheiten>Plug-In für Eclipse</Softwarebesonderheiten>
        </Software>
        <!--Software besteht aus ID, Namen,Beschreibung und Besonderheiten -->
        <Software ID="Eclipse">
            <Softwarename>Eclipse</Softwarename>
            <Softwarebeschreibung>IDE
                    <hersteller>Eclipse</hersteller>
            </Softwarebeschreibung>
            <Softwarebesonderheiten> Version veraltet </Softwarebesonderheiten>
        </Software>
        <Software ID="Java">
            <Softwarename>Java</Softwarename>
            <Softwarebeschreibung>
            		Programmierung
                    <hersteller>Oracle</hersteller>
            </Softwarebeschreibung>
            <Softwarebesonderheiten>Objektorientierte Programmierungsprache</Softwarebesonderheiten>
        </Software>
        <Software ID="VIM">
            <Softwarename>VIM</Softwarename>
            <Softwarebeschreibung>
            		Textverarbeitung
                    <hersteller>vim</hersteller>
            </Softwarebeschreibung>
            <Softwarebesonderheiten>Sehr Leitungsstark</Softwarebesonderheiten>
        </Software>
        
        <weitere_Geraete WeiteresID="01">
            <Art>Beamer</Art>
            <Beschreibung>
                    <hersteller>BenQ</hersteller>
            </Beschreibung>
        </weitere_Geraete>
        <!-- weitere_geraete auch nicht notwendig können auftauchen müssen aber nicht -->
        <weitere_Geraete WeiteresID="02">
        <!-- Eindeutige ID für jedes Gerät-->
            <Art>Drucker</Art>
            <!--Art des gerätes (Name)-->
            <Beschreibung>Schöner Drucker von
                    <hersteller>HP</hersteller>
            </Beschreibung>
            <!-- auch wieder mixed content, Beschreibungen teilen sich einen Typen -->
        </weitere_Geraete>
    </Labor>
    <!-- Mindestens 1 Labor nötig können aber auch mehr sein, sowie ein Computer -->
    <Labor Name="Labor02" Raum="Raum02">
    <!-- Labor muss anderen namen und Raum ahben, 2 Laore in einem Raum oder 2 Räume in einem Labor 
    haben für uns eher ekinen Sinn gemacht
    -->
        <Computer RechnerId="Rechner01">
            <Betriebssystem>MAc OS</Betriebssystem>
            <Anschaffung>2002-09-24</Anschaffung>
            <Erweiterungen>
            	<Beschreibung> Mainboard von <hersteller>MSI</hersteller> nachgerüstet, sowie 20 TB SSD von <hersteller>Samsung</hersteller> </Beschreibung>        
            </Erweiterungen>
            <Rechnerbeschreibung>   
                    <hersteller>NVIDIA</hersteller>
            </Rechnerbeschreibung>
            <Rechnerbesonderheiten>Keine</Rechnerbesonderheiten>
            <Software2 Id="Eclipse"/>
            <Software2 Id="VIM"/>
        </Computer>
        <Software ID="Eclipse">
            <Softwarename>Eclipse</Softwarename>
            <Softwarebeschreibung>
                    <hersteller>Eclipse</hersteller>
            </Softwarebeschreibung>
            <Softwarebesonderheiten>Für Fortgeschrittene</Softwarebesonderheiten>
        </Software>
        <!-- Selbe Definition wie oben aber okay da anderes Labor -->
        <Software ID="VIM">
            <Softwarename>VIM</Softwarename>
            <Softwarebeschreibung>
            		Textverarbeitung
                    <hersteller>vim</hersteller>
            </Softwarebeschreibung>
            <Softwarebesonderheiten>Sehr Leitungsstark, how to exit?</Softwarebesonderheiten>
        </Software>
        <Software ID="Java">
            <Softwarename>Java</Softwarename>
            <Softwarebeschreibung>
            		Programmierung
                    <hersteller>Oracle</hersteller>
            </Softwarebeschreibung>
            <Softwarebesonderheiten>Objektorientierte Programmierungsprache</Softwarebesonderheiten>
        </Software>
        <weitere_Geraete WeiteresID="01">
            <Art>Beamer</Art>
            <Beschreibung>
                    <hersteller>Logitech</hersteller>
            </Beschreibung>
        </weitere_Geraete>
        <!--Andere Räume dürfen dieselbe ID haben für Geräte etc, da der Raum sie schon spezifisch auseinanderhällt -->
    </Labor>
</Labordaten>

=== Hossein3041/programmieren_3/src/Erster_Assignment/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<Labordaten xmlns="assignment01.webprog.de"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="assignment01.webprog.de Assignment1.xsd">
    <Labor Name="Labor01" Raum="Raum01">
        <Computer RechnerId="Rechner01">
            <Betriebssystem>MAc OS</Betriebssystem>
            <Anschaffung>2002-09-24</Anschaffung>
            <Erweiterungen>
                    <Beschreibung>
                        <Hersteller>NVIDIA</Hersteller>
                    </Beschreibung>
                    <Besonderheiten>Keine</Besonderheiten>
            </Erweiterungen>
            <Rechnerbeschreibung>
                    <Hersteller>NVIDIA</Hersteller>
            </Rechnerbeschreibung>
            <Rechnerbesonderheiten>Keine</Rechnerbesonderheiten>
            <Software2 lizensiert="true" Id="Eclipse"/>
        </Computer>
        <Software ID="Eclipse">
            <Softwarename>Eclipse</Softwarename>
            <Softwarebeschreibung>
                    <Hersteller>NVIDIA</Hersteller>
            </Softwarebeschreibung>
            <Softwarebesonderheiten>Keine</Softwarebesonderheiten>
        </Software>
        <weitere_Geraete>
            <Art>Beamer</Art>
            <Beschreibung>
                    <Hersteller>NVIDIA</Hersteller>
            </Beschreibung>
        </weitere_Geraete>
    </Labor>
</Labordaten>
