<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persons [
    <!ELEMENT lastname (#PCDATA)>
    <!ELEMENT firstname (#PCDATA)>
    <!ELEMENT residence (#PCDATA)>
    <!ELEMENT children (person*)>
    <!ELEMENT person (firstname, (lastname?), (children?), (residence?))>
    <!ELEMENT persons (person+)>
    <!ATTLIST person id ID #REQUIRED>
    <!ATTLIST person friends IDREFS #IMPLIED>
	<!ATTLIST persons file CDATA #IMPLIED>
    ]>
<?mach was draus?>
<persons file="this">
    <!-- Hier beginnen die Daten -->
    <person id="p-2">
        <firstname>Pu</firstname>
        <lastname>Bär</lastname>
        <children>
            <person id="p-9" friends=" p-2 p-3 ">
                <firstname>Max Mustermann</firstname>
                <residence>Maxstadt Musterland</residence>
            </person>
        </children>
    </person>
    <person id="p-1">
        <firstname>Christopher</firstname>
        <lastname>Robin</lastname>
        <children>
            <person id="p-10" friends=" p-4 p-6 ">
                <firstname>Karrote Zwiebelmann</firstname>
                <children>
                    <person id="p-16" friends=" p-10 p-15">
                        <firstname> Justun Bieber </firstname>
                        <lastname> Berlin </lastname>
                    </person>
                </children>
                <residence>Planet der Affen</residence>
            </person>
        </children>
    </person>
    <person id="p-3">
        <firstname>Eule</firstname>
        <residence>Hundertsechzig-Morgen-Wald</residence>
    </person>
    <person id="p-4">
        <firstname>I-Ah</firstname>
    </person>
    <person id="p-5">
        <firstname>Kängah</firstname>
        <children>
            <person id="p-6" friends=" p-1 p-7 ">
                <firstname>Klein Ruh</firstname>
                <!-- Kommentar bei Klein Ruh -->
                <residence>Bei Kängah</residence>
            </person>
        </children>
        <residence>Bei Kängah</residence>
        <!-- zusätzlich -->
    </person>
    <person id="p-7">
        <firstname>Tieger</firstname>
        <residence>Bei Kängah</residence>
    </person>
    <person id="p-8" friends="p-1">
        <firstname>Ferkel<!-- Kommentar bei Ferkel--></firstname>
        <children>
            <person id="p-11" friends=" p-6 p-10 ">
                <firstname>Joe Biden</firstname>
                <children>
                    <person id="p-15" friends=" p-8 p-10">
                        <firstname> Bill Clinton</firstname>
                        <lastname> New York</lastname>
                    </person>
                </children>
                <residence>Waschington DC</residence>
            </person>
        </children>
    </person>
    <!-- Kommentar zum Schluss -->
    <?tu was damit?>
</persons>
